### PR TITLE
Remove FileQuery. Expect a list of files instead.

### LINKED ISSUE #31: generateFilePaths excludes files with absolute path
`generateFilePaths` excludes valid file paths because when an absolute path is passed, `filePath` is initialized to a relative path

```dart
@override
Iterable<String> generateFilePaths() sync* {
  final dir = Directory(dirPath);
  for (final fse
      in dir.listSync(followLinks: followLinks, recursive: recursive)) {
    if (fse is! File) {
      continue;
    }
    final filePath = p.relative(fse.absolute.path); // convert to relative path
    if (!pathLooksLikeCode(filePath)) {...}
    ...
}
```

which means that `pathLooksLikeCode` will always return false because the path starts with `.`.

```dart
bool pathLooksLikeCode(String filePath) =>
    !filePath.contains('/.') &&
    !(filePath.startsWith('.') && !filePath.startsWith('./')) &&
    !filePath.startsWith('build/');
```

In my opinion this is unexpected behavior I would propose removing that condition in order to allow for absolute paths. Thoughts? Thanks!

### PR DESCRIPTION
**Pull request by evanweible-wf**
**This is a breaking change and if accepted, should be introduced in at least an 0.2.0 release.**

## Motivation
Fixes #31 and makes it simpler to build the input set for codemods.

## Changes
- Remove `FileQuery` (it's functionality can be replaced with `Glob.listSync` and `Directory.listSync` as well as manual list building)

## Todo
- Update documentation accordingly

## Release Notes
TODO

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

File: lib/src/file_query_util.dart [hunk 1]
```diff
@@ -12,12 +12,22 @@
...
-  await dev(args);
+bool isHiddenFile(File file) {
+  final path = p.normalize(file.path);
+  return p.basename(path).startsWith('.') ||
+      p.split(path).any((segment) => segment.startsWith('.'));
 }
+
+bool isNotHiddenFile(File file) => !isHiddenFile(file);
+
+bool isDartHiddenFile(File file) {
```
Comment (greglittlefield-wf) [inline lib/src/file_query_util.dart]: `isDartHiddenFile` and `isHiddenFile` would probably be used in almost all use-cases, right?

I don't think you'd want to codemod files inside `.dart_tool`, and you'd most likely want to skip hidden directories like `.git`/`.idea`/`.vscode`.

It might be nice if these were opt-out so that codemod authors don't accidentally forget to add them.

File: lib/src/file_query_util.dart [hunk 2]
```diff
@@ -12,12 +12,22 @@
...
+  final path = p.normalize(file.path);
+  return p.basename(path) == '.packages' ||
+      p.split(p.normalize(path)).any((segment) => segment == '.dart_tool');
```
Comment (greglittlefield-wf) [inline lib/src/file_query_util.dart]: #nit This could be simplified (path is already normalized)
```suggestion
      p.split(path).contains('.dart_tool');
```

File: lib/src/run_interactive_codemod.dart [hunk 3]
```diff
@@ -201,23 +200,24 @@ int _runInteractiveCodemod(
...
 
-  List<Patch> skippedPatches = [];
+  List<Patch> skippedPatches = <Patch>[];
   stdout.writeln('searching...');
   for (final suggestor in suggestors) {
-    final filePaths = query.generateFilePaths().toList()..sort();
-    for (final filePath in filePaths) {
-      logger.fine('file: $filePath');
+    final sortedFiles = files.toList()
+      ..sort((a, b) => a.path.compareTo(b.path));
```
Comment (greglittlefield-wf) [inline lib/src/run_interactive_codemod.dart]: Not super important, but is there a reason files are sorted alphabetically instead of on the order they're queried in?

File: lib/src/file_query_util.dart (hunk 1 above)
Comment (smaifullerton-wk) [reply lib/src/file_query_util.dart]: ^ Agreed

File: lib/src/run_interactive_codemod.dart (hunk 3 above)
Comment (evanweible-wf) [reply lib/src/run_interactive_codemod.dart]: I can't remember why I did that ¯\_(ツ)_/¯  Probably makes more sense to keep them in order they are provided.. that would also allow us to potentially benefit from a sync generator

File: lib/src/file_query_util.dart (hunk 1 above)
Comment (evanweible-wf) [reply lib/src/file_query_util.dart]: Yeah, that's fair. So what do you think about an optional param on `runInteractiveCodemod` to disable the filtering-out of these hidden files?

```dart
// Runs on `.dart` files, but filters out hidden files/dirs by default
runInteractiveCodemod(
  Glob('**.dart').listSync(recursive: true).whereType<File>(),
  suggestor);

// Runs on `.dart` files that are known to be in a hidden directory, so the
// filtering of hidden files is disabled
runInteractiveCodemod(
  Glob('.dart_tool/build/generated/**.dart').listSync(recursive: true).whereType<File>(),
  suggestor,
  ignoreHiddenFiles: false);
```

Comment (greglittlefield-wf) [reply lib/src/file_query_util.dart]: I like it!

File: lib/src/run_interactive_codemod.dart (hunk 3 above)
Comment (greglittlefield-wf) [reply lib/src/run_interactive_codemod.dart]: Noice, lazy :allthethings:!

File: lib/src/file_query_util.dart (hunk 1 above)
Comment (evanweible-wf) [reply lib/src/file_query_util.dart]: I guess another option would be to keep something like `FIleQuery` around just for the purpose of building file input sets more easily.. that way all of the listing/filtering logic is contained within `FileQuery` and `runInteractiveCodemod` runs on exactly what it is given (i.e. `Iterable<File>`) and doesn't do any additional filtering or require any additional params.

```dart
class FileQuery implements Set<File> {
  FileQuery.fromGlob(Glob glob, {bool ignoreHiddenFiles = true});
  FileQuery.fromIterable(Iterable<File> files);
}

// Single glob, ignores hidden files by default (common use case)
final files = FileQuery.fromGlob(Glob('**.dart', recursive: true));

// Individual files (common use case)
final files = ['pubspec.yaml', 'build.yaml'];

// Combine multiple input sets
final files = {'pubspec.yaml', 'build.yaml'}
    .union(FileQuery.fromGlob(Glob('**.dart', recursive: true)));

// Use globs with more specific exclusions
final files = FileQuery.fromGlob(Glob('**.dart', recursive: true))
    .difference(FileQuery.fromGlob(Glob('build/**', recursive: true)));

// Disable hidden file filtering for special use cases
final files = FileQuery.fromGlob(
    Glob('.dart_tool/build/generated/**.dart', recursive: true),
    ignoreHiddenFiles: false);

runInteractiveCodemod(files, suggestor, ...);
```

Thoughts?

Comment (greglittlefield-wf) [reply lib/src/file_query_util.dart]: While I like having all of the file filtering logic decoupled from `runInteractiveCodemod`, it seems less convenient to have to have another layer around the Glob, and it's not immediately obvious what FileQuery is providing on top of Glob's functionality.

---

If we do end up moving forward with that approach,  does making FileQuery a class provide any benefit, or can we just use functions?

```dart
-final files = FileQuery.fromGlob(Glob('**.dart', recursive: true));
+final files = queryFilesFromGlob(Glob('**.dart', recursive: true));
```

**Comment by evanweible-wf** [comment]
@greglittlefield-wf I addressed your comments if you'd like to take another look!

**Comment by evanweible-wf** [comment]
QA +1
- [x] CI passes and tested locally

Merging into wip branch, will open a new PR to master with couple more small changes + changelog update. @Workiva/release-management-p
